---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-website

# ---
# apiVersion: getambassador.io/v2
# kind: Mapping
# metadata:
#   name: quote-backend
#   namespace: demo-website
# spec:
#   prefix: /give-me-a-quote/
#   service: quote

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ambassador-ingress
  namespace: demo-website
spec:
  ingressClassName: ambassador
  rules:
  - http:
      paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: quote
              port:
                number: 80
    host: www.demowebsite.local

---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: demo-website
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: quote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  namespace: demo-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: demo-website
      labels:
        app: quote
    spec:
      containers:
        - name: backend
          image: docker.io/datawire/quote:0.4.1
          ports:
            - containerPort: 8080
