apiVersion: v1
kind: Namespace
metadata:
  name: demo-db

---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-db
  name: mongodb
  labels:
    app: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30007
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful
  namespace: demo-db
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      namespace: demo-db
      labels:
        app: mongodb
    spec:
      nodeSelector:
        role: mongodb
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
        namespace: demo-db
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 30Gi      


